name: roberta-bilstm-env
channels:
  - pytorch
  - nvidia      # Parametro para usar CUDA
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  
  # PyTorch (Ajuste o pytorch-cuda para a versão do seu driver)
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  
  # Ferramentas Científicas e de Machine Learning
  - scikit-learn
  - numpy<2.0.0
  - tqdm
  - nltk
  - matplotlib

  # Pacotes de configuração do python
  - pillow
  - python-dotenv
  
  # Ecossistema Hugging Face
  - pip
  - pip:
      - transformers==4.37.0
      - datasets==2.16.1
      - huggingface-hub
